config:
  backup: true
  banner: true
  create: true
  dotpath: ./
  ignoreempty: false
  keepdot: false
  link_by_default: false
  longkey: false
  showdiff: false
  workdir: ~/.config/dotdrop
dotfiles:
  d_beet:
    dst: ~/.config/beets
    src: config/beets
  d_bin:
    dst: ~/bin
    src: bin
  d_desktop:
    dst: ~/.local/share/applications
    src: local/share/applications
  d_docker:
    dst: ~/.docker
    src: docker
  d_dunst:
    dst: ~/.config/dunst
    src: config/dunst
  d_git:
    dst: ~/.gitconfig.d
    src: gitconfig.d
  d_i3:
    dst: ~/.config/i3
    src: config/i3
  d_i3_status:
    dst: ~/.config/i3status
    src: config/i3status
  d_mopidy:
    dst: ~/.config/mopidy
    src: config/mopidy
  d_neovim:
    dst: ~/.config/nvim
    link_children: true
    src: config/nvim
  d_ranger:
    dst: ~/.config/ranger
    src: config/ranger
  d_ssh:
    dst: ~/.ssh
    link_children: true
    src: ssh
  d_sway:
    dst: ~/.config/sway
    src: config/sway
  d_termite:
    dst: ~/.config/termite
    src: config/termite
  d_tmux:
    dst: ~/.tmux.d
    src: tmux.d
  d_vim:
    dst: ~/.vim
    link_children: true
    src: vim
  f_abcde:
    dst: ~/.abcde.conf
    src: abcde.conf
  f_bash:
    dst: ~/.bashrc
    src: bashrc
  f_bash_aliases:
    dst: ~/.bash_aliases
    src: bash_aliases
  f_bash_profile:
    dst: ~/.bash_profile
    src: bash_profile
  f_ctags:
    dst: ~/.ctags
    src: ctags
  f_git:
    dst: ~/.gitconfig
    src: gitconfig
  f_git_ignore:
    dst: ~/.gitignore
    src: gitignore
  f_ledger:
    dst: ~/.ledgerrc
    src: ledgerrc
  f_mopidy_service:
    dst: ~/.config/systemd/user/mopidy.service
    src: config/systemd/user/mopidy.service
  f_msmtprc:
    dst: ~/.msmtprc
    src: msmtprc
  f_profile:
    dst: ~/.profile
    src: profile
  f_silver_search_ag:
    dst: ~/.agignore
    src: agignore
  f_tmux:
    dst: ~/.tmux.conf
    src: tmux.conf
  f_xdg_dirs:
    dst: ~/.config/user-dirs.dirs
    src: config/user-dirs.dirs
  f_xinit:
    dst: ~/.xinitrc
    src: xinitrc
  f_xprofile:
    dst: ~/.xprofile
    src: xprofile
  f_xresources:
    dst: ~/.Xresources
    src: Xresources
  f_yaml_linter:
    dst: ~/.yamllintrc
    src: yamllintrc
dynvariables:
  spotify_client_id: 'pass db/Loisir/Spotify | grep ''^client_id'' | tr '': '' ''

    '' | tail -1'
  spotify_client_secret: 'pass db/Loisir/Spotify | grep ''^client_secret'' | tr '':
    '' ''

    '' | tail -1'
  spotify_password: pass db/Loisir/Spotify | head -1
  spotify_username: 'pass db/Loisir/Spotify | grep ''^login'' | tr '': '' ''

    '' | tail -1'
profiles:
  LAPTOP-EBARRACO:
    dotfiles:
    - d_bin
    - d_desktop
    - d_dunst
    - d_docker
    - d_git
    - d_i3
    - d_i3_status
    - d_mopidy
    - d_neovim
    - d_ranger
    - d_ssh
    - d_sway
    - d_termite
    - d_tmux
    - d_vim
    - f_abcde
    - f_bash
    - f_bash_aliases
    - f_bash_profile
    - f_ctags
    - f_git
    - f_git_ignore
    - f_ledger
    - f_mopidy_service
    - f_profile
    - f_silver_search_ag
    - f_tmux
    - f_xdg_dirs
    - f_xinit
    - f_xprofile
    - f_xresources
    - f_yaml_linter
    - f_msmtprc
    variables:
      git_email: e.barraco@ubitransport.com
      git_smtp_encryption: tls
      git_smtp_port: 587
      git_smtp_server: smtp.gmail.com
      git_smtp_user: e.barraco@ubitransport.com
      msmtp_default_profile: ubitransport
  Terminator:
    dotfiles:
    - d_beet
    - d_bin
    - d_desktop
    - d_dunst
    - d_docker
    - d_git
    - d_i3
    - d_i3_status
    - d_mopidy
    - d_neovim
    - d_ranger
    - d_ssh
    - d_sway
    - d_termite
    - d_tmux
    - d_vim
    - f_abcde
    - f_bash
    - f_bash_aliases
    - f_bash_profile
    - f_ctags
    - f_git
    - f_git_ignore
    - f_ledger
    - f_mopidy_service
    - f_profile
    - f_silver_search_ag
    - f_tmux
    - f_xdg_dirs
    - f_xinit
    - f_xprofile
    - f_xresources
    - f_yaml_linter
    - f_msmtprc
  flying-jesusraptor:
    dotfiles:
    - d_bin
    - d_desktop
    - d_dunst
    - d_docker
    - d_git
    - d_i3
    - d_i3_status
    - d_mopidy
    - d_neovim
    - d_ranger
    - d_ssh
    - d_sway
    - d_termite
    - d_tmux
    - d_vim
    - f_abcde
    - f_bash
    - f_bash_aliases
    - f_bash_profile
    - f_ctags
    - f_git
    - f_git_ignore
    - f_ledger
    - f_mopidy_service
    - f_profile
    - f_silver_search_ag
    - f_tmux
    - f_xdg_dirs
    - f_xinit
    - f_xprofile
    - f_xresources
    - f_yaml_linter
    - f_msmtprc
  prodb:
    dotfiles:
    - d_docker
    - d_vim
    - d_neovim
    - f_bash
    - f_bash_aliases
    - f_bash_profile
    - f_tmux
variables:
  git_email: contact@eddiebarraco.fr
  git_smtp_encryption: tls
  git_smtp_port: 587
  git_smtp_server: mail.misterbanal.net
  git_smtp_user: contact@eddiebarraco.fr
  msmtp_default_profile: personal
